# 4.4 异常

45. 不要使用 `try/catch` 块进行流程控制。
46. 只捕获 `catch` 你可以处理的异常。 
47. 永远不要定义空 `catch` 块。 
48. 避免在 `catch` 块中嵌套 `try/catch`。 
49. 始终通过异常过滤器捕获最多派生的异常。 
50. 从最多到最少派生的异常类型排序异常过滤器。 
51. 避免重新抛出异常。允许它冒泡抛出。 
52. 如果重新抛出异常，则通过省略 `throw` 中的异常参数来保留原始调用的堆栈声明。  
**Example**:
    ```C#
    // Bad! 
    catch(Exception ex) 
    {
        Log(ex);
        throw ex; 
    }

    // Good! 
    catch(Exception) 
    {
        Log(ex);
        throw; 
    }
    ```
53. 仅使用 `finally` 块从 `try` 语句中释放资源。
54. 始终使用验证来避免异常。  
**Example**：
    ```C#
    // Bad! 
    try 
    {
        conn.Close(); 
    } 
    catch(Exception ex) 
    {
        // handle exception if already closed! 
    }

    // Good!
    if(conn.State != ConnectionState.Closed) 
    { 
        conn.Close(); 
    }
    ```
55. 始终在抛出的异常上设置 `innerException` 属性，以便异常链和调用堆栈可维护。 
56. 避免定义自定义异常类。请改用现有的异常类。 
57. 当需要自定义异常时；  
    a. 始终从 `Exception` 而不是  `ApplicationException` 中派生。  
    b. 始终在自定义异常类名称后面加上 "Exception"后缀。  
    c. 始终将 `SerializableAttribute` 添加到异常类。  
    d. 始终实现标准的 “异常构造函数模式”：     `public MyCustomException ();`
    `public MyCustomException (string message);`
    `public MyCustomException (string message，Exception innerException);`  
    e. 始终实现反序列化构造函数：  
    `protected MyCustomException(SerializationInfo info,StreamingContext contxt);`
58. 始终在自定义异常类上设置适当的 `HResult` 值。  
(**Note**：ApplicationException HResult = -2146232832)
59. 定义包含其他属性的自定义异常类时：  
a. 始终重写 `Message` 属性，`ToString()` 方法和隐式运算符字符串，包括自定义属性值。  
b. 始终修改反序列化构造函数以检索自定义属性值。  
c. 始终重写 `GetObjectData (...) 方法以将自定义属性添加到序列化集合。  
**Example**：
    ```C#
    public override void GetObjectData(SerializationInfo info, StreamingContext context) 
    { 
        base.GetObjectData (info, context);

        info.AddValue("MyValue", _myValue);
    }
    ```